variable "environment" {}
variable "imagename" {}
variable "instance_type" {}
variable "key_name" {}
variable "sg" {}
variable "vpc_name" {}
variable "public-subnets" {}
variable "private-subnets" {}
variable "ngw_depends_on" {} 
variable "iam_instance_profile" {}